Decryption/ttcc 1511
bonobos/tap-sftp pull request #3
Opened 2021-02-16 14:40 UTC by pnadolny13

- add decryption module to pull the file, decrypt, then continue processing as usual
- "tables" config was previously required to be a string of encoded json which was stupid and a huge pain so now its just a list in the main json config
- AWS SSM module for pulling the decryption key when needed
- the singer_encoding module was abstracted out to its own package but we needed to customize it for decryption so I just copied it as a sub module
- fixed all codecoverage formatting issues

For storing decryption keys we evaluated options for assuming the host machine has the keys configured prior to running, pulling/importing from SSM, or passing the key in as a config file variable. The config variable worked but was too big for APS to handle (4KB max for KMS encryption) due to large table configs in the config file. Requiring the host env to have the key imported prior to running would require APS to have custom stfp tap logic to handle importing keys which we chose to avoid. The SSM route was best, all sftp logic including key importing is done in the tap as long as an SSM parameter is configured with the private key in AWS.

PENDING: tox tests

2021-02-16 19:47 UTC, timf-bonobos commented on tap_sftp/singer_encodings/csv.py
> +SDC_EXTRA_COLUMN = "_sdc_extra"
I'm assuming thing this a specific SFMC

2021-02-16 19:50 UTC, timf-bonobos commented on tap_sftp/singer_encodings/csv.py
> +SDC_EXTRA_COLUMN = "_sdc_extra"
Also, you should rename this file to target_csv.py otherwise if you import csv it will overwrite the default python library `csv`

2021-02-16 19:51 UTC, timf-bonobos commented on tap_sftp/singer_encodings/json_schema.py
> +SDC_SOURCE_FILE_COLUMN = "_sdc_source_file"
I haven't seen this before, am I missing something in the singer framework?

2021-02-16 19:52 UTC, timf-bonobos requested changes
There is some specific logic in this repo for SFMC - so it's really a SFTP_SFMC_TAP.
A few things, but I'll add more when I do another pass

2021-02-16 22:03 UTC, pnadolny13 commented on tap_sftp/singer_encodings/json_schema.py
> +SDC_SOURCE_FILE_COLUMN = "_sdc_source_file"
honestly not sure what SDC stands for but theyre just metadata columns specific to this tap. Its attaching the file name the record came from along with the line number. Might be overkill but also might be useful

2021-02-16 22:05 UTC, pnadolny13 commented
> There is some specific logic in this repo for SFMC - so it's really a SFTP_SFMC_TAP.
> A few things, but I'll add more when I do another pass

Those columns arent SFMC specific - it should be truly agnostic. The only thing is the DEGism of pulling decryption keys from SSM.

2021-02-18 20:56 UTC, timf-bonobos approved these changes
looks good only 1 comment about confest.

2021-02-18 20:56 UTC, timf-bonobos commented on tests/configuration/fixtures.py
> +from pathlib import Path
This could just be a conftest.py in the root of the pytest with your other tests and you wouldn't need to import- as pytest loads it automatically.

The only overhead is that the fixtures are loaded into each test.

2021-02-25 19:18 UTC, timf-bonobos approved these changes

2021-02-26 18:32 UTC, merged